In [1]:
import pandas as pd

In [2]:
# read excel

df = pd.read_excel('transactions preprocessed.xlsx')

In [ ]:
#check columns

df.columns

Index(['Unnamed: 0.2', 'Unnamed: 0.1', 'Transaction Name',
       'Transaction Name URL', 'Organization Name', 'Organization Name URL',
       'Funding Type', 'Money Raised', 'Money Raised Currency',
       'Money Raised Currency (in USD)', 'Announced Date', 'Investor Names',
       'Funding Stage', 'Number of Investors', 'Organization Description',
       'Organization Industries', 'Organization Location',
       'Organization Revenue Range', 'Total Funding Amount',
       'Total Funding Amount Currency',
       'Total Funding Amount Currency (in USD)', 'Funding Status',
       'Number of Funding Rounds', 'Lead Investors',
       'Total Funding Amount (in USD)', 'Organization Website', 'Unnamed: 0',
       'Organization Name_y', 'whu', 'WHU Company', 'Announced Day',
       'Announced Month', 'Announced Year'],
      dtype='object')

In [4]:
# select all observations with funding type 'Seed'
df_seed = df[df['Funding Type'] == 'Seed']

# create list with all uniqe values for Announced Year
announced_years = df_seed['Announced Year'].unique()

#sort the list

announced_years.sort()

In [5]:
announced_years

array([2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024, 2025])

In [6]:
# create empty list to store the number of transactions per year

seed_transactions_list = []

# loop through the list of announced years and count the number of transactions for each year, then append the count to the list

for year in announced_years:
    seed_transactions_year = df_seed[df_seed['Announced Year'] == year].shape[0]
    seed_transactions_list.append(seed_transactions_year)

In [7]:
# check the list

seed_transactions_list

[183, 268, 302, 418, 380, 333, 375, 297, 316, 490, 443, 333, 282, 264]

In [8]:
# create unique list of funding types
funding_types = df['Funding Type'].unique()

In [11]:
# create empty dictionary to store the number of transactions per year for each funding type
funding_type_transactions = {}

# loop through the list of funding types, then for each funding type loop through the list of announced years and count the number of transactions for each year, then append the count to the list and add the list to the dictionary with the funding type as key
for funding_type in funding_types:
    df_funding_type = df[df['Funding Type'] == funding_type]
    transactions_list = []
    for year in announced_years:
        transactions_year = df_funding_type[df_funding_type['Announced Year'] == year].shape[0]
        transactions_list.append(transactions_year)
    funding_type_transactions[funding_type] = transactions_list

In [12]:
# check the dictionary

funding_type_transactions

{'Seed': [183,
  268,
  302,
  418,
  380,
  333,
  375,
  297,
  316,
  490,
  443,
  333,
  282,
  264],
 'Pre-Seed': [7, 15, 29, 21, 36, 63, 142, 174, 206, 234, 238, 195, 140, 146],
 'Grant': [8, 8, 30, 100, 99, 99, 89, 96, 44, 36, 35, 0, 89, 101],
 'Venture - Series Unknown': [107,
  123,
  105,
  118,
  128,
  142,
  124,
  98,
  77,
  175,
  106,
  116,
  104,
  83],
 'Series A': [54, 76, 79, 87, 105, 109, 120, 131, 115, 139, 142, 124, 94, 93],
 'Funding Round': [1, 7, 11, 13, 14, 21, 21, 12, 15, 21, 24, 0, 15, 19],
 'Post-IPO Equity': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 15, 20],
 'Post-IPO Debt': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 26, 42],
 'Convertible Note': [1, 5, 4, 15, 18, 17, 20, 19, 35, 29, 19, 0, 14, 10],
 'Private Equity': [17, 22, 20, 33, 29, 35, 32, 28, 20, 28, 25, 0, 28, 23],
 'Corporate Round': [7, 3, 5, 5, 7, 20, 19, 20, 20, 20, 15, 0, 19, 22],
 'Angel': [18, 19, 47, 40, 38, 34, 28, 17, 15, 46, 62, 0, 17, 12],
 'Series C': [9, 11, 16, 21, 22, 17, 16, 23, 21, 25, 16, 10, 14, 13],
 'Debt Financing': [4, 4, 9, 10, 17, 20, 26, 13, 29, 32, 58, 0, 43, 67],
 'Equity Crowdfunding': [3, 11, 3, 8, 9, 14, 11, 4, 6, 3, 2, 0, 7, 3],
 'Series B': [21, 25, 40, 42, 41, 38, 51, 49, 42, 70, 48, 32, 40, 27],
 'Series D': [7, 4, 5, 7, 4, 9, 11, 6, 10, 19, 12, 4, 7, 2],
 'Non-equity Assistance': [1,
  5,
  14,
  26,
  38,
  19,
  36,
  48,
  44,
  41,
  29,
  0,
  30,
  17],
 'Secondary Market': [1, 1, 7, 2, 1, 1, 5, 5, 1, 4, 4, 0, 4, 10],
 'Series G': [0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1],
 'Post-IPO Secondary': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 3, 2],
 'Series E': [0, 2, 3, 5, 4, 4, 3, 3, 3, 5, 6, 2, 2, 1],
 'Initial Coin Offering': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0],
 'Series F': [0, 1, 1, 2, 1, 1, 3, 2, 1, 1, 1, 4, 1, 0],
 'Product Crowdfunding': [0, 4, 8, 10, 2, 2, 3, 1, 1, 0, 1, 0, 0, 0],
 'Series H': [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]}

In [13]:
#transform dictionary to dataframe
funding_type_transactions_df = pd.DataFrame(funding_type_transactions, index=announced_years)

In [ ]:
# check the dataframe

funding_type_transactions_df

,Seed,Pre-Seed,Grant,Venture - Series Unknown,Series A,Funding Round,Post-IPO Equity,Post-IPO Debt,Convertible Note,Private Equity,...,Series D,Non-equity Assistance,Secondary Market,Series G,Post-IPO Secondary,Series E,Initial Coin Offering,Series F,Product Crowdfunding,Series H
2012,183,7,8,107,54,1,0,0,1,17,...,7,1,1,0,0,0,0,0,0,0
2013,268,15,8,123,76,7,0,0,5,22,...,4,5,1,0,0,2,0,1,4,0
2014,302,29,30,105,79,11,0,0,4,20,...,5,14,7,1,0,3,0,1,8,0
2015,418,21,100,118,87,13,0,0,15,33,...,7,26,2,0,0,5,0,2,10,1
2016,380,36,99,128,105,14,0,0,18,29,...,4,38,1,2,0,4,0,1,2,1
2017,333,63,99,142,109,21,0,0,17,35,...,9,19,1,0,0,4,0,1,2,1
2018,375,142,89,124,120,21,0,0,20,32,...,11,36,5,0,0,3,0,3,3,0
2019,297,174,96,98,131,12,0,0,19,28,...,6,48,5,0,0,3,0,2,1,0
2020,316,206,44,77,115,15,0,0,35,20,...,10,44,1,0,0,3,0,1,1,0
2021,490,234,36,175,139,21,0,0,29,28,...,19,41,4,1,0,5,0,1,0,0
2022,443,238,35,106,142,24,23,9,19,25,...,12,29,4,0,2,6,2,1,1,0
2023,333,195,0,116,124,0,0,0,0,0,...,4,0,0,0,0,2,0,4,0,0
2024,282,140,89,104,94,15,15,26,14,28,...,7,30,4,2,3,2,2,1,0,0
2025,264,146,101,83,93,19,20,42,10,23,...,2,17,10,1,2,1,0,0,0,0

In [15]:
# transform name column Seed into column Number Seed Transactions
funding_type_transactions_df = funding_type_transactions_df.rename(columns={'Seed': 'Seed Transactions'})

# rename every column with name of funding type + ' Transactions'
funding_type_transactions_df = funding_type_transactions_df.rename(columns={funding_type: funding_type + ' Transactions' for funding_type in funding_types})

In [17]:
# check the dataframe

funding_type_transactions_df

,Seed Transactions,Pre-Seed Transactions,Grant Transactions,Venture - Series Unknown Transactions,Series A Transactions,Funding Round Transactions,Post-IPO Equity Transactions,Post-IPO Debt Transactions,Convertible Note Transactions,Private Equity Transactions,...,Series D Transactions,Non-equity Assistance Transactions,Secondary Market Transactions,Series G Transactions,Post-IPO Secondary Transactions,Series E Transactions,Initial Coin Offering Transactions,Series F Transactions,Product Crowdfunding Transactions,Series H Transactions
2012,183,7,8,107,54,1,0,0,1,17,...,7,1,1,0,0,0,0,0,0,0
2013,268,15,8,123,76,7,0,0,5,22,...,4,5,1,0,0,2,0,1,4,0
2014,302,29,30,105,79,11,0,0,4,20,...,5,14,7,1,0,3,0,1,8,0
2015,418,21,100,118,87,13,0,0,15,33,...,7,26,2,0,0,5,0,2,10,1
2016,380,36,99,128,105,14,0,0,18,29,...,4,38,1,2,0,4,0,1,2,1
2017,333,63,99,142,109,21,0,0,17,35,...,9,19,1,0,0,4,0,1,2,1
2018,375,142,89,124,120,21,0,0,20,32,...,11,36,5,0,0,3,0,3,3,0
2019,297,174,96,98,131,12,0,0,19,28,...,6,48,5,0,0,3,0,2,1,0
2020,316,206,44,77,115,15,0,0,35,20,...,10,44,1,0,0,3,0,1,1,0
2021,490,234,36,175,139,21,0,0,29,28,...,19,41,4,1,0,5,0,1,0,0
2022,443,238,35,106,142,24,23,9,19,25,...,12,29,4,0,2,6,2,1,1,0
2023,333,195,0,116,124,0,0,0,0,0,...,4,0,0,0,0,2,0,4,0,0
2024,282,140,89,104,94,15,15,26,14,28,...,7,30,4,2,3,2,2,1,0,0
2025,264,146,101,83,93,19,20,42,10,23,...,2,17,10,1,2,1,0,0,0,0

In [18]:
# create empty dictionary to store the number of transactions per year for each funding type for WHU companies
funding_type_transactions_whu = {}

# loop through the list of funding types, then for each funding type loop through the list of announced years and count the number of transactions for each year for WHU companies, then append the count to the list and add the list to the dictionary with the funding type as key
for funding_type in funding_types:
    df_funding_type = df[df['Funding Type'] == funding_type]
    transactions_list = []
    for year in announced_years:
        transactions_year = df_funding_type[(df_funding_type['Announced Year'] == year) & (df_funding_type['WHU Company'] == 1)].shape[0]
        transactions_list.append(transactions_year)
    funding_type_transactions_whu[funding_type] = transactions_list

In [19]:
# transform dictionary to dataframe

funding_type_transactions_whu_df = pd.DataFrame(funding_type_transactions_whu, index=announced_years)

In [20]:
# rename every column with name of funding type + ' Transactions'
funding_type_transactions_whu_df = funding_type_transactions_whu_df.rename(columns={funding_type: funding_type + ' WHU Transactions' for funding_type in funding_types})

In [21]:
# check the dataframe

funding_type_transactions_whu_df

,Seed WHU Transactions,Pre-Seed WHU Transactions,Grant WHU Transactions,Venture - Series Unknown WHU Transactions,Series A WHU Transactions,Funding Round WHU Transactions,Post-IPO Equity WHU Transactions,Post-IPO Debt WHU Transactions,Convertible Note WHU Transactions,Private Equity WHU Transactions,...,Series D WHU Transactions,Non-equity Assistance WHU Transactions,Secondary Market WHU Transactions,Series G WHU Transactions,Post-IPO Secondary WHU Transactions,Series E WHU Transactions,Initial Coin Offering WHU Transactions,Series F WHU Transactions,Product Crowdfunding WHU Transactions,Series H WHU Transactions
2012,11,0,0,14,4,0,0,0,0,2,...,0,0,1,0,0,0,0,0,0,0
2013,12,1,1,6,4,0,0,0,0,2,...,0,1,1,0,0,0,0,0,0,0
2014,19,2,0,9,9,3,0,0,0,1,...,2,0,1,0,0,0,0,0,0,0
2015,30,0,1,10,9,1,0,0,0,2,...,1,0,0,0,0,3,0,1,0,0
2016,24,1,4,14,8,1,0,0,3,2,...,0,1,0,1,0,1,0,0,0,0
2017,25,2,2,11,11,1,0,0,0,1,...,1,0,1,0,0,0,0,0,0,0
2018,16,4,0,10,13,0,0,0,1,0,...,1,2,1,0,0,1,0,0,0,0
2019,20,7,1,5,14,0,0,0,0,0,...,1,0,1,0,0,0,0,1,0,0
2020,18,9,1,4,7,1,0,0,1,1,...,3,1,1,0,0,0,0,0,0,0
2021,22,9,0,18,15,2,0,0,0,2,...,1,0,0,1,0,0,0,0,0,0
2022,27,11,1,9,10,0,0,1,1,0,...,2,1,0,0,0,0,0,0,0,0
2023,19,12,0,4,7,0,0,0,0,0,...,2,0,0,0,0,1,0,0,0,0
2024,17,5,0,8,4,0,0,0,0,2,...,1,0,0,0,0,1,0,0,0,0
2025,10,8,1,8,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
# merge both dataframes on index
funding_type_transactions_merged = pd.merge(funding_type_transactions_df, funding_type_transactions_whu_df, left_index=True, right_index=True)

In [24]:
# check the merged dataframe

funding_type_transactions_merged.head()

,Seed Transactions,Pre-Seed Transactions,Grant Transactions,Venture - Series Unknown Transactions,Series A Transactions,Funding Round Transactions,Post-IPO Equity Transactions,Post-IPO Debt Transactions,Convertible Note Transactions,Private Equity Transactions,...,Series D WHU Transactions,Non-equity Assistance WHU Transactions,Secondary Market WHU Transactions,Series G WHU Transactions,Post-IPO Secondary WHU Transactions,Series E WHU Transactions,Initial Coin Offering WHU Transactions,Series F WHU Transactions,Product Crowdfunding WHU Transactions,Series H WHU Transactions
2012,183,7,8,107,54,1,0,0,1,17,...,0,0,1,0,0,0,0,0,0,0
2013,268,15,8,123,76,7,0,0,5,22,...,0,1,1,0,0,0,0,0,0,0
2014,302,29,30,105,79,11,0,0,4,20,...,2,0,1,0,0,0,0,0,0,0
2015,418,21,100,118,87,13,0,0,15,33,...,1,0,0,0,0,3,0,1,0,0
2016,380,36,99,128,105,14,0,0,18,29,...,0,1,0,1,0,1,0,0,0,0

In [25]:
# export to excel

funding_type_transactions_merged.to_excel('funding_type_transactions_merged.xlsx')

In [58]:
# aggregate data for funding type by Money Raised Currency (in USD)

# start with seed only

seed_money_list = []

for year in announced_years:
    seed_money_year = df_seed[df_seed['Announced Year'] == year]['Money Raised Currency (in USD)'].sum()
    seed_money_list.append(seed_money_year)

seed_money_list

[np.float64(39925819.0),
 np.float64(56013247.0),
 np.float64(98152195.0),
 np.float64(154287936.0),
 np.float64(157147239.0),
 np.float64(189899158.0),
 np.float64(297811060.0),
 np.float64(269349879.0),
 np.float64(496936906.0),
 np.float64(1058701254.0),
 np.float64(1186798144.0),
 np.float64(732572959.0),
 np.float64(863900355.0),
 np.float64(932905128.0)]

In [59]:
# for every funding type, create list with money raised per year

funding_type_money = {}
for funding_type in funding_types:
    df_funding_type = df[df['Funding Type'] == funding_type]
    money_list = []
    for year in announced_years:
        money_year = df_funding_type[df_funding_type['Announced Year'] == year]['Money Raised Currency (in USD)'].sum()
        money_list.append(money_year)
    funding_type_money[funding_type] = money_list

# create dataframe from dictionary

funding_type_money_df = pd.DataFrame(funding_type_money, index=announced_years)

# rename every column with name of funding type + ' Money Raised (in USD)'
funding_type_money_df = funding_type_money_df.rename(columns={funding_type: funding_type + ' Money Raised (in USD)' for funding_type in funding_types})

funding_type_money_df

,Seed Money Raised (in USD),Pre-Seed Money Raised (in USD),Grant Money Raised (in USD),Venture - Series Unknown Money Raised (in USD),Series A Money Raised (in USD),Funding Round Money Raised (in USD),Post-IPO Equity Money Raised (in USD),Post-IPO Debt Money Raised (in USD),Convertible Note Money Raised (in USD),Private Equity Money Raised (in USD),...,Series D Money Raised (in USD),Non-equity Assistance Money Raised (in USD),Secondary Market Money Raised (in USD),Series G Money Raised (in USD),Post-IPO Secondary Money Raised (in USD),Series E Money Raised (in USD),Initial Coin Offering Money Raised (in USD),Series F Money Raised (in USD),Product Crowdfunding Money Raised (in USD),Series H Money Raised (in USD)
2012,3.992582e+07,936214.0,8.008200e+05,2.499919e+08,1.033934e+08,0.0,0.000000e+00,0.000000e+00,64530.0,4.520631e+08,...,1.998165e+08,0.0,3.755296e+08,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0
2013,5.601325e+07,876628.0,1.637345e+07,7.092121e+08,2.838339e+08,3595440.0,0.000000e+00,0.000000e+00,6666800.0,1.991866e+08,...,6.377129e+07,16888639.0,0.000000e+00,0.0,0.0,7.898734e+07,0.0,6500000.0,1394695.0,0.0
2014,9.815220e+07,4165942.0,1.531898e+07,8.353181e+08,2.464713e+08,452224057.0,0.000000e+00,0.000000e+00,54511.0,2.359925e+08,...,2.203931e+08,0.0,0.000000e+00,350000000.0,0.0,1.092983e+08,0.0,85000000.0,9210583.0,0.0
2015,1.542879e+08,4305637.0,5.216044e+07,4.130557e+08,3.323507e+08,5559123.0,0.000000e+00,0.000000e+00,739741.0,4.559677e+08,...,2.091168e+08,1669797.0,5.484538e+07,0.0,0.0,4.642268e+08,0.0,193612145.0,11589574.0,561213579.0
2016,1.571472e+08,5928756.0,6.815692e+07,4.085397e+08,4.735681e+08,111692700.0,0.000000e+00,0.000000e+00,29564762.0,5.864673e+08,...,1.364276e+08,488659.0,0.000000e+00,110059282.0,0.0,1.145961e+08,0.0,29500000.0,813402.0,4670329.0
2017,1.898992e+08,8860669.0,6.169564e+07,4.643943e+08,6.855528e+08,450444720.0,0.000000e+00,0.000000e+00,2293823.0,7.735555e+08,...,2.755861e+08,1219670.0,0.000000e+00,0.0,0.0,5.054424e+08,0.0,169500000.0,361778.0,2364066.0
2018,2.978111e+08,24638074.0,5.034547e+07,1.939802e+09,9.698172e+08,55546315.0,0.000000e+00,0.000000e+00,33238892.0,2.241906e+09,...,4.119981e+08,752498.0,5.482936e+06,0.0,0.0,8.810374e+07,0.0,667272474.0,486575.0,0.0
2019,2.693499e+08,37886111.0,8.683447e+07,7.508775e+08,8.689594e+08,1854221.0,0.000000e+00,0.000000e+00,22801366.0,9.585488e+08,...,1.130385e+09,28833023.0,2.214849e+07,0.0,0.0,7.352406e+08,0.0,563056722.0,206307.0,0.0
2020,4.969369e+08,52145133.0,1.143304e+09,1.125074e+09,9.955055e+08,21325645.0,0.000000e+00,0.000000e+00,479879037.0,6.177568e+08,...,3.816296e+08,766764.0,0.000000e+00,0.0,0.0,1.715011e+08,0.0,0.0,207000.0,0.0
2021,1.058701e+09,98298833.0,1.340664e+08,3.109740e+09,2.038087e+09,137905957.0,0.000000e+00,0.000000e+00,133689707.0,1.446915e+09,...,3.091434e+09,3024779.0,0.000000e+00,650000000.0,0.0,1.658970e+09,0.0,175000000.0,0.0,0.0
2022,1.186798e+09,524991401.0,7.818179e+07,1.466140e+09,2.087206e+09,392606597.0,9.800737e+09,4.641500e+09,576977716.0,4.450253e+08,...,1.929877e+09,127815.0,5.085613e+07,0.0,89329789.0,8.214979e+08,5113464.0,33840206.0,386611.0,0.0
2023,7.325730e+08,143547566.0,0.000000e+00,1.424465e+09,1.411061e+09,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,...,3.359540e+08,0.0,0.000000e+00,0.0,0.0,1.297466e+08,0.0,386996973.0,0.0,0.0
2024,8.639004e+08,110935311.0,1.408376e+09,1.226091e+09,1.113515e+09,925634458.0,1.132202e+09,3.717111e+10,23103627.0,1.127046e+09,...,3.412175e+08,154513.0,2.677342e+06,264919608.0,810732025.0,2.334016e+08,60000000.0,62997873.0,0.0,0.0
2025,9.329051e+08,159303702.0,2.550689e+09,1.352234e+09,1.772182e+09,51323474.0,6.946518e+09,3.713946e+10,189441378.0,1.071484e+09,...,6.889369e+08,1605213.0,2.032490e+09,144593893.0,63250000.0,1.764534e+08,0.0,0.0,0.0,0.0

In [60]:
# we need to address missing values. If no transactions exist value should be NaN instead of 0
funding_type_money = {}
for funding_type in funding_types:
    df_funding_type = df[df['Funding Type'] == funding_type]
    money_list = []
    for year in announced_years:
        if df_funding_type[df_funding_type['Announced Year'] == year].shape[0] == 0:
            money_year = None

        else:
            money_year = df_funding_type[df_funding_type['Announced Year'] == year]['Money Raised Currency (in USD)'].sum()
        money_list.append(money_year)
    funding_type_money[funding_type] = money_list

# create dataframe from dictionary

funding_type_money_df = pd.DataFrame(funding_type_money, index=announced_years)

# rename every column with name of funding type + ' Money Raised (in USD)'
funding_type_money_df = funding_type_money_df.rename(columns={funding_type: funding_type + ' Money Raised (in USD)' for funding_type in funding_types})

funding_type_money_df

,Seed Money Raised (in USD),Pre-Seed Money Raised (in USD),Grant Money Raised (in USD),Venture - Series Unknown Money Raised (in USD),Series A Money Raised (in USD),Funding Round Money Raised (in USD),Post-IPO Equity Money Raised (in USD),Post-IPO Debt Money Raised (in USD),Convertible Note Money Raised (in USD),Private Equity Money Raised (in USD),...,Series D Money Raised (in USD),Non-equity Assistance Money Raised (in USD),Secondary Market Money Raised (in USD),Series G Money Raised (in USD),Post-IPO Secondary Money Raised (in USD),Series E Money Raised (in USD),Initial Coin Offering Money Raised (in USD),Series F Money Raised (in USD),Product Crowdfunding Money Raised (in USD),Series H Money Raised (in USD)
2012,3.992582e+07,936214.0,8.008200e+05,2.499919e+08,1.033934e+08,0.0,NaN,NaN,64530.0,4.520631e+08,...,1.998165e+08,0.0,3.755296e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013,5.601325e+07,876628.0,1.637345e+07,7.092121e+08,2.838339e+08,3595440.0,NaN,NaN,6666800.0,1.991866e+08,...,6.377129e+07,16888639.0,0.000000e+00,NaN,NaN,7.898734e+07,NaN,6500000.0,1394695.0,NaN
2014,9.815220e+07,4165942.0,1.531898e+07,8.353181e+08,2.464713e+08,452224057.0,NaN,NaN,54511.0,2.359925e+08,...,2.203931e+08,0.0,0.000000e+00,350000000.0,NaN,1.092983e+08,NaN,85000000.0,9210583.0,NaN
2015,1.542879e+08,4305637.0,5.216044e+07,4.130557e+08,3.323507e+08,5559123.0,NaN,NaN,739741.0,4.559677e+08,...,2.091168e+08,1669797.0,5.484538e+07,NaN,NaN,4.642268e+08,NaN,193612145.0,11589574.0,561213579.0
2016,1.571472e+08,5928756.0,6.815692e+07,4.085397e+08,4.735681e+08,111692700.0,NaN,NaN,29564762.0,5.864673e+08,...,1.364276e+08,488659.0,0.000000e+00,110059282.0,NaN,1.145961e+08,NaN,29500000.0,813402.0,4670329.0
2017,1.898992e+08,8860669.0,6.169564e+07,4.643943e+08,6.855528e+08,450444720.0,NaN,NaN,2293823.0,7.735555e+08,...,2.755861e+08,1219670.0,0.000000e+00,NaN,NaN,5.054424e+08,NaN,169500000.0,361778.0,2364066.0
2018,2.978111e+08,24638074.0,5.034547e+07,1.939802e+09,9.698172e+08,55546315.0,NaN,NaN,33238892.0,2.241906e+09,...,4.119981e+08,752498.0,5.482936e+06,NaN,NaN,8.810374e+07,NaN,667272474.0,486575.0,NaN
2019,2.693499e+08,37886111.0,8.683447e+07,7.508775e+08,8.689594e+08,1854221.0,NaN,NaN,22801366.0,9.585488e+08,...,1.130385e+09,28833023.0,2.214849e+07,NaN,NaN,7.352406e+08,NaN,563056722.0,206307.0,NaN
2020,4.969369e+08,52145133.0,1.143304e+09,1.125074e+09,9.955055e+08,21325645.0,NaN,NaN,479879037.0,6.177568e+08,...,3.816296e+08,766764.0,0.000000e+00,NaN,NaN,1.715011e+08,NaN,0.0,207000.0,NaN
2021,1.058701e+09,98298833.0,1.340664e+08,3.109740e+09,2.038087e+09,137905957.0,NaN,NaN,133689707.0,1.446915e+09,...,3.091434e+09,3024779.0,0.000000e+00,650000000.0,NaN,1.658970e+09,NaN,175000000.0,NaN,NaN
2022,1.186798e+09,524991401.0,7.818179e+07,1.466140e+09,2.087206e+09,392606597.0,9.800737e+09,4.641500e+09,576977716.0,4.450253e+08,...,1.929877e+09,127815.0,5.085613e+07,NaN,89329789.0,8.214979e+08,5113464.0,33840206.0,386611.0,NaN
2023,7.325730e+08,143547566.0,NaN,1.424465e+09,1.411061e+09,NaN,NaN,NaN,NaN,NaN,...,3.359540e+08,NaN,NaN,NaN,NaN,1.297466e+08,NaN,386996973.0,NaN,NaN
2024,8.639004e+08,110935311.0,1.408376e+09,1.226091e+09,1.113515e+09,925634458.0,1.132202e+09,3.717111e+10,23103627.0,1.127046e+09,...,3.412175e+08,154513.0,2.677342e+06,264919608.0,810732025.0,2.334016e+08,60000000.0,62997873.0,NaN,NaN
2025,9.329051e+08,159303702.0,2.550689e+09,1.352234e+09,1.772182e+09,51323474.0,6.946518e+09,3.713946e+10,189441378.0,1.071484e+09,...,6.889369e+08,1605213.0,2.032490e+09,144593893.0,63250000.0,1.764534e+08,NaN,NaN,NaN,NaN

In [61]:
# additional issues with missing values. Transactions that did not disclose money raised should not be considered

# we need to address missing values. If no transactions exist value should be NaN instead of 0
funding_type_money = {}
for funding_type in funding_types:
    df_funding_type = df[df['Funding Type'] == funding_type]
    money_list = []
    for year in announced_years:
        if df_funding_type[df_funding_type['Announced Year'] == year].shape[0] == 0:
            money_year = None

        else:
            cleaned_df = df_funding_type[(df_funding_type['Announced Year'] == year) & (df_funding_type['Money Raised Currency (in USD)'].notna())]
            if cleaned_df.shape[0] == 0:
                money_year = None
            else:
                money_year = cleaned_df['Money Raised Currency (in USD)'].sum()
        money_list.append(money_year)
    funding_type_money[funding_type] = money_list

# create dataframe from dictionary

funding_type_money_df = pd.DataFrame(funding_type_money, index=announced_years)

# rename every column with name of funding type + ' Money Raised (in USD)'
funding_type_money_df = funding_type_money_df.rename(columns={funding_type: funding_type + ' Money Raised (in USD)' for funding_type in funding_types})

funding_type_money_df

,Seed Money Raised (in USD),Pre-Seed Money Raised (in USD),Grant Money Raised (in USD),Venture - Series Unknown Money Raised (in USD),Series A Money Raised (in USD),Funding Round Money Raised (in USD),Post-IPO Equity Money Raised (in USD),Post-IPO Debt Money Raised (in USD),Convertible Note Money Raised (in USD),Private Equity Money Raised (in USD),...,Series D Money Raised (in USD),Non-equity Assistance Money Raised (in USD),Secondary Market Money Raised (in USD),Series G Money Raised (in USD),Post-IPO Secondary Money Raised (in USD),Series E Money Raised (in USD),Initial Coin Offering Money Raised (in USD),Series F Money Raised (in USD),Product Crowdfunding Money Raised (in USD),Series H Money Raised (in USD)
2012,3.992582e+07,936214.0,8.008200e+05,2.499919e+08,1.033934e+08,NaN,NaN,NaN,64530.0,4.520631e+08,...,1.998165e+08,NaN,3.755296e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013,5.601325e+07,876628.0,1.637345e+07,7.092121e+08,2.838339e+08,3595440.0,NaN,NaN,6666800.0,1.991866e+08,...,6.377129e+07,16888639.0,NaN,NaN,NaN,7.898734e+07,NaN,6500000.0,1394695.0,NaN
2014,9.815220e+07,4165942.0,1.531898e+07,8.353181e+08,2.464713e+08,452224057.0,NaN,NaN,54511.0,2.359925e+08,...,2.203931e+08,NaN,NaN,350000000.0,NaN,1.092983e+08,NaN,85000000.0,9210583.0,NaN
2015,1.542879e+08,4305637.0,5.216044e+07,4.130557e+08,3.323507e+08,5559123.0,NaN,NaN,739741.0,4.559677e+08,...,2.091168e+08,1669797.0,5.484538e+07,NaN,NaN,4.642268e+08,NaN,193612145.0,11589574.0,561213579.0
2016,1.571472e+08,5928756.0,6.815692e+07,4.085397e+08,4.735681e+08,111692700.0,NaN,NaN,29564762.0,5.864673e+08,...,1.364276e+08,488659.0,NaN,110059282.0,NaN,1.145961e+08,NaN,29500000.0,813402.0,4670329.0
2017,1.898992e+08,8860669.0,6.169564e+07,4.643943e+08,6.855528e+08,450444720.0,NaN,NaN,2293823.0,7.735555e+08,...,2.755861e+08,1219670.0,NaN,NaN,NaN,5.054424e+08,NaN,169500000.0,361778.0,2364066.0
2018,2.978111e+08,24638074.0,5.034547e+07,1.939802e+09,9.698172e+08,55546315.0,NaN,NaN,33238892.0,2.241906e+09,...,4.119981e+08,752498.0,5.482936e+06,NaN,NaN,8.810374e+07,NaN,667272474.0,486575.0,NaN
2019,2.693499e+08,37886111.0,8.683447e+07,7.508775e+08,8.689594e+08,1854221.0,NaN,NaN,22801366.0,9.585488e+08,...,1.130385e+09,28833023.0,2.214849e+07,NaN,NaN,7.352406e+08,NaN,563056722.0,206307.0,NaN
2020,4.969369e+08,52145133.0,1.143304e+09,1.125074e+09,9.955055e+08,21325645.0,NaN,NaN,479879037.0,6.177568e+08,...,3.816296e+08,766764.0,NaN,NaN,NaN,1.715011e+08,NaN,NaN,207000.0,NaN
2021,1.058701e+09,98298833.0,1.340664e+08,3.109740e+09,2.038087e+09,137905957.0,NaN,NaN,133689707.0,1.446915e+09,...,3.091434e+09,3024779.0,NaN,650000000.0,NaN,1.658970e+09,NaN,175000000.0,NaN,NaN
2022,1.186798e+09,524991401.0,7.818179e+07,1.466140e+09,2.087206e+09,392606597.0,9.800737e+09,4.641500e+09,576977716.0,4.450253e+08,...,1.929877e+09,127815.0,5.085613e+07,NaN,89329789.0,8.214979e+08,5113464.0,33840206.0,386611.0,NaN
2023,7.325730e+08,143547566.0,NaN,1.424465e+09,1.411061e+09,NaN,NaN,NaN,NaN,NaN,...,3.359540e+08,NaN,NaN,NaN,NaN,1.297466e+08,NaN,386996973.0,NaN,NaN
2024,8.639004e+08,110935311.0,1.408376e+09,1.226091e+09,1.113515e+09,925634458.0,1.132202e+09,3.717111e+10,23103627.0,1.127046e+09,...,3.412175e+08,154513.0,2.677342e+06,264919608.0,810732025.0,2.334016e+08,60000000.0,62997873.0,NaN,NaN
2025,9.329051e+08,159303702.0,2.550689e+09,1.352234e+09,1.772182e+09,51323474.0,6.946518e+09,3.713946e+10,189441378.0,1.071484e+09,...,6.889369e+08,1605213.0,2.032490e+09,144593893.0,63250000.0,1.764534e+08,NaN,NaN,NaN,NaN

In [62]:
# for every funding type, create list with money raised from whu companies per year
funding_type_whu_money = {}
for funding_type in funding_types:
    df_funding_type = df[df['Funding Type'] == funding_type]
    df_whu = df_funding_type[df_funding_type['WHU Company'] == 1]
    money_list = []
    for year in announced_years:
        if df_whu[df_whu['Announced Year'] == year].shape[0] == 0:
            money_year = None
        else:
            cleaned_df = df_whu[(df_whu['Announced Year'] == year) & (df_whu['Money Raised Currency (in USD)'].notna())]
            if cleaned_df.shape[0] == 0:
                money_year = None
            else:
                money_year = cleaned_df['Money Raised Currency (in USD)'].sum()
        money_list.append(money_year)
    funding_type_whu_money[funding_type] = money_list

# create dataframe from dictionary
funding_type_whu_money_df = pd.DataFrame(funding_type_whu_money, index=announced_years)

# rename every column with name of funding type + ' WHU Money Raised (in USD)'
funding_type_whu_money_df = funding_type_whu_money_df.rename(columns={funding_type: funding_type + ' WHU Money Raised (in USD)' for funding_type in funding_types})

funding_type_whu_money_df

,Seed WHU Money Raised (in USD),Pre-Seed WHU Money Raised (in USD),Grant WHU Money Raised (in USD),Venture - Series Unknown WHU Money Raised (in USD),Series A WHU Money Raised (in USD),Funding Round WHU Money Raised (in USD),Post-IPO Equity WHU Money Raised (in USD),Post-IPO Debt WHU Money Raised (in USD),Convertible Note WHU Money Raised (in USD),Private Equity WHU Money Raised (in USD),...,Series D WHU Money Raised (in USD),Non-equity Assistance WHU Money Raised (in USD),Secondary Market WHU Money Raised (in USD),Series G WHU Money Raised (in USD),Post-IPO Secondary WHU Money Raised (in USD),Series E WHU Money Raised (in USD),Initial Coin Offering WHU Money Raised (in USD),Series F WHU Money Raised (in USD),Product Crowdfunding WHU Money Raised (in USD),Series H WHU Money Raised (in USD)
2012,300000.0,NaN,NaN,45202038.0,7687902.0,NaN,None,NaN,NaN,50000000.0,...,NaN,NaN,375529601.0,NaN,None,NaN,None,NaN,None,None
2013,1479650.0,260531.0,NaN,530475887.0,23000000.0,NaN,None,NaN,NaN,187703289.0,...,NaN,6337648.0,NaN,NaN,None,NaN,None,NaN,None,None
2014,10176361.0,34358.0,NaN,589877862.0,31591913.0,444895128.0,None,NaN,NaN,98764077.0,...,110000000.0,NaN,NaN,NaN,None,NaN,None,NaN,None,None
2015,6921297.0,NaN,82656.0,206341681.0,33314609.0,NaN,None,NaN,NaN,29594834.0,...,NaN,NaN,NaN,NaN,None,336000000.0,None,85637358.0,None,None
2016,10944007.0,NaN,322634.0,93916868.0,55717387.0,3337887.0,None,NaN,27587321.0,90000000.0,...,NaN,NaN,NaN,88321782.0,None,NaN,None,NaN,None,None
2017,16891100.0,NaN,4714626.0,19722406.0,83170971.0,431450000.0,None,NaN,NaN,NaN,...,25948077.0,NaN,NaN,NaN,None,NaN,None,NaN,None,None
2018,21362874.0,NaN,NaN,59026682.0,69089204.0,NaN,None,NaN,NaN,NaN,...,35027987.0,NaN,NaN,NaN,None,17103743.0,None,NaN,None,None
2019,47993008.0,2910626.0,NaN,41260398.0,94245232.0,NaN,None,NaN,NaN,NaN,...,114000000.0,NaN,22148492.0,NaN,None,NaN,None,563056722.0,None,None
2020,21935720.0,8148116.0,1019909.0,14585445.0,65585359.0,3000000.0,None,NaN,NaN,NaN,...,66394810.0,NaN,NaN,NaN,None,NaN,None,NaN,None,None
2021,45789666.0,5390224.0,NaN,287946592.0,211508670.0,NaN,None,NaN,NaN,168228500.0,...,47824007.0,NaN,NaN,650000000.0,None,NaN,None,NaN,None,None
2022,155903201.0,9295576.0,1000000.0,197803533.0,192184712.0,NaN,None,101918514.0,NaN,NaN,...,470000000.0,NaN,NaN,NaN,None,NaN,None,NaN,None,None
2023,56802485.0,14364020.0,NaN,56974979.0,87445269.0,NaN,None,NaN,NaN,NaN,...,280754040.0,NaN,NaN,NaN,None,65007741.0,None,NaN,None,None
2024,63194012.0,8312153.0,NaN,151382050.0,79567914.0,NaN,None,NaN,NaN,NaN,...,26319862.0,NaN,NaN,NaN,None,NaN,None,NaN,None,None
2025,34184335.0,11967898.0,NaN,490777818.0,109565498.0,NaN,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,None,NaN,None,NaN,None,None

In [63]:
# merge both dataframes on index

funding_type_money_merged = pd.merge(funding_type_money_df, funding_type_whu_money_df, left_index=True, right_index=True, how='outer')  
funding_type_money_merged.head()

,Seed Money Raised (in USD),Pre-Seed Money Raised (in USD),Grant Money Raised (in USD),Venture - Series Unknown Money Raised (in USD),Series A Money Raised (in USD),Funding Round Money Raised (in USD),Post-IPO Equity Money Raised (in USD),Post-IPO Debt Money Raised (in USD),Convertible Note Money Raised (in USD),Private Equity Money Raised (in USD),...,Series D WHU Money Raised (in USD),Non-equity Assistance WHU Money Raised (in USD),Secondary Market WHU Money Raised (in USD),Series G WHU Money Raised (in USD),Post-IPO Secondary WHU Money Raised (in USD),Series E WHU Money Raised (in USD),Initial Coin Offering WHU Money Raised (in USD),Series F WHU Money Raised (in USD),Product Crowdfunding WHU Money Raised (in USD),Series H WHU Money Raised (in USD)
2012,39925819.0,936214.0,800820.0,249991939.0,103393350.0,NaN,NaN,NaN,64530.0,452063077.0,...,NaN,NaN,375529601.0,NaN,None,NaN,None,NaN,None,None
2013,56013247.0,876628.0,16373450.0,709212133.0,283833898.0,3595440.0,NaN,NaN,6666800.0,199186600.0,...,NaN,6337648.0,NaN,NaN,None,NaN,None,NaN,None,None
2014,98152195.0,4165942.0,15318981.0,835318141.0,246471332.0,452224057.0,NaN,NaN,54511.0,235992516.0,...,110000000.0,NaN,NaN,NaN,None,NaN,None,NaN,None,None
2015,154287936.0,4305637.0,52160437.0,413055717.0,332350699.0,5559123.0,NaN,NaN,739741.0,455967661.0,...,NaN,NaN,NaN,NaN,None,336000000.0,None,85637358.0,None,None
2016,157147239.0,5928756.0,68156924.0,408539681.0,473568137.0,111692700.0,NaN,NaN,29564762.0,586467254.0,...,NaN,NaN,NaN,88321782.0,None,NaN,None,NaN,None,None

In [64]:
# export to excel
funding_type_money_merged.to_excel('funding_type_money_merged.xlsx')